### ISSUE TITLE
Add support for podcasts

### ISSUE THREAD

**Issue by maihde** [maihde/roku_subsonic#15]
Add support for podcasts using the podcast API

**Comment by skywaymsn** [comment]
+1 I was looking for this last night.  Please provide a suggested donation amount for this feature.

**Comment by maihde** [comment]
This feature should be straight forward to add, I see if I can get to in
the next week or so.  I'll post again when I have a test version for you to
try.

Donations are greatly appreciated but not required.  When the feature is
finished feel free to give as little or as much as you choose.

~Michael

**Comment by maihde** [comment]
If you have the chance, please try to install this 1.9 release candidate:

https://owner.roku.com/add/Z5EV5

You may need to delete the current version you have installed.  The 1.9
release candidate includes podcast support...please let me know if it
doesn't work for you.

**Comment by skywaymsn** [comment]
The two can live together, you just have to know which is which.

The new beta is great!  I messed around with the podcasts last night.  I noticed two things: 1) There is a distinct lag between selecting a podcast and the audio starting, but this may be more about disk access on my backend.  2) There is title, but no date information on the available podcasts making it difficult to determine order.

If the API exposes date information about a podcast, adding it to the display would be great.  Other than that, it's pretty solid.

-Matt

**Comment by maihde** [comment]
I've just published an update that fixes item (2).  Let me know if your a
happy with the change.

As for item (1), the lag would be outside of my control.  With the Roku
device I have to provide it the streamURL and then it deals with all the
details of fetching the content.  On my system with a classic Roku I don't
observe any noticeable lag.

Try hitting your Subsonic server with the below URL (obviously replacing
the host, port, uname, and pword):

http://localhost:4040/rest/getPodcasts.view?u=uname&p=pword&v=1.7.0&c=test

and look at the reported contentType.  It it's not 'audio/mpeg' then the
server is performing transcoding and perhaps that is the source of the lag.

You can also see how long it takes SubSonic to send the stream by reading
the streamId from the getPodcasts.view and sending it to this URL

http://localhost:4040/rest/stream.view?u=uname&p=pword&v=1.7.0&c=test&id=streamId


If that is having noticeable lag, then it something about your subsonic
server.  If that is fast...then either the network or the Roku is the
issue.  If the later, it would most likely be caused by the device/firmware
that you have.  If you provide those details to me I'll scour the
documents/forums to see if anybody else has had issues.

Cheers,
~Michael

**Comment by maihde** [comment]
Matt, any luck with the new update?

**Comment by skywaymsn** [comment]
I've been out of town for a few days.  I'll fire it up tonight and let you know.

**Comment by skywaymsn** [comment]
Looks great!

**Comment by maihde** [comment]
Cool.  I'm going to publish it then so it becomes the official version
(which will also automatically update).

~Michael
