### ISSUE TITLE
Stuck at Retrieving when browsing all artists

### ISSUE THREAD

**Issue by mkosel** [maihde/roku_subsonic#22]
I currently have a Roku 2 that is connected to my home network via a wired ethernet connection. I am running Windows Server 2012 R2, plex Media server and Madsonic Server 5.1 (via non-SSL). I have installed and configured the this subsonic-app on my Roku.  the connection works as expected

The problem I am having I that I can't play music from Roku when I browse all artists. when I select browse, I get the expected list of artists that I can choose from... however when I click on an artist name, the roku change goes to "retrieving" and never starts playing the music.

The strange thing is if I go to a random album that is listed on the home-screen , it plays fine. I can also play music if I use the web interface from another, computer.  any thoughts?

**Comment by maihde** [comment]
Just checking to see if you have had the opportunity to test this yet.

Cheers,
~Michael

**Comment by mkosel** [comment]
I appologize for not email back sooner..... I did install the new subsnic
app but it didn't work....  I haven't had time to trouble shoot yet.  The
updates app deosn't work at all.... when I clikc on the icon from the roku
channel list, it says loading and nothing else happens.

It is possible I may be having problems with the fact that I have the old
and new version of the app installed... i'm hoping to est this this week

thanks again for your work in getting this out

Matt

**Comment by maihde** [comment]
No worries, I just wanted to make sure that the email got to you.

On my Roku 2 all I had to do was click the new link and open the channel
store (and then close it without doing anything).  I ended up with two
copies of the Subsonic app on my channel screen.

If for some reason it is still giving you troubles, I can publish the new
updated version.  This will upgrade *all* Roku-Subsonic installations.

Cheers,
~Michael

**Comment by mkosel** [comment]
I got the channel installed fone but I can't get it to open. Can you
provide the new link

**Comment by maihde** [comment]
Try deleting all of the Subsonic applications and then installing from this
link:

https://owner.roku.com/add/RHNBT

That should install the 1.8.0 release candidate, you can verify this from
the settings screen.  I'll also have one of my friends with a Roku 3 try
the same.

Cheers,
~Michael

**Comment by mkosel** [comment]
I just want to let you know that I've been using the new roku client for 
the last 4-5 days and it works perfectly.  I had a bit of trouble 
installing the new version but once I got the update setup it has worked 
flawlessly.  I sent a donation your way to thank you for your time.  Let 
me know if there is something else I can do to help

Matt

**Comment by maihde** [comment]
That's great that everything is working!  The donation is much appreciated.

I've just officially published the 1.8 version soon.  The way Roku handles
this is the version you are currently running will now be available as the
default version.  It will also automatically upgrade all players that
currently have the 1.7 version installed.

Because you are running an unpublished version (which I greatly appreciate
since it helped with the testing), I'm not sure what will happen on your
Roku, it may uninstall automatically or it may just leave it as is.
Unfortunately I cannot control what how Roku handles this.  The safe bet is
to re-install from the primary link.

Thanks again!

~Michael
